### ISSUE TITLE
Unable to push views (segue or programatically)

### ISSUE THREAD

**Issue by oworsnop** [uacaps/PageMenu#11]
Hi,

1st thing - loving this controller!

I am trying to push a segue when a collectionviewcell is pressed, however I am getting the below error:
- Terminating app due to uncaught exception 'NSGenericException', reason: 'Could not find a navigation controller for segue 'ViewController'. Push segues can only be used when the source controller is managed by an instance of UINavigationController.'

I am assuming this is due to the nav actually being a subview? Do you know of anyways around this? I have tried embedding my viewcontroller in a uinavigationcontroller but to no avail.

Thanks!

**Comment by fahlout** [comment]
In order to push anything from a tap on a cell you will have to pass the navigation controller of the parent view controller that contains the page menu and then push onto the parent view controller navigation controller from the table view controller or collection view controller. The next release will have one of the demos updated to show this behavior. If I don't release anything today you can check the develop branch as it will probably have a commit for this

**Comment by oworsnop** [comment]
Awesome, i'll watch out for it! :)

**Comment by nandof06** [comment]
Awesomw controller!!!! I havent been able to push a segue either. I am trying with demo 3 following the sameway in your demo 5 in the last branch. Is it possible to find a tutorial or explanation on this subject?
Thanks!

**Comment by fahlout** [comment]
are you trying to have multiple page menu's in one view like demo3? Demo 3 has some bugs right now and should probably not be used. I will probably have to redo that demo from scratch. Either way, currently in order to push you need to push from the navigation controller that contains the parent view controller of page menu, so the view controller containing page menu. Then when setting up the view controller array any view controller that needs to push needs to have a property for the parent navigation controller and have it be set when creating the view controller instances for the array. After that you can push onto that navigation controller from any of the view controllers that you have set up the parent navigation controller property in. Hope that helps

**Comment by nandof06** [comment]
Thanks for your answer. I was trying to push segue with a didSelectRowAtIndexPath into a new viewcontroller in the storyboard. I haven't been able to setup.

**Comment by fahlout** [comment]
if you set it up following my instructions and the demo you should be able to get it working as that is the only way to make it work as of right now

**Comment by wizmeister** [comment]
To help everyone on how to do it:

On the View Controller you want to push set a property:

var navController = UINavigationController()

Then, on the View Controller that has the PageMenu (thanks, again fahlout!), on viewDidLoad, when you instantiate the view controllers do as such:

var controller3 = mainStoryboard.instantiateViewControllerWithIdentifier("identifier") as controller3
controller3.navController = self.navigationController!

then add your controller to your controllers array as you would normally do.

**Comment by Bautistax** [comment]
![viewcontroller](https://cloud.githubusercontent.com/assets/7776448/6095148/3a4ede36-af13-11e4-8f6b-f737b733342c.png)

but instead of calling nibs, how do i directly call a view controller from the MainStoryBoard by calling its class name? (as you can see at the pic), i outlet a tableview with cells on the view controller and won't show anything, just show the background of the uiview

**Comment by wizmeister** [comment]
My example is based on the storyboard demo... Look at the demos and you will see.

**Comment by Bautistax** [comment]
@wizmeister whats your email? so i can send you the project

**Comment by wizmeister** [comment]
@Bautistax you can instantiate your view controllers using storyboard like this:

first, you set storyboard identifier on your view controller (from the inspector)

then this is how you instantiate the view controller (although there is an example made by @fahlout, I write again):

```
let mainStoryboard: UIStoryboard = UIStoryboard(name: "Main",bundle: nil)
var controller : UIViewController = mainStoryboard.instantiateViewControllerWithIdentifier("vcIdentifier") as UIViewController
```

**Comment by Bautistax** [comment]
thank you so much @wizmeister  
😃

**Comment by wizmeister** [comment]
So, I am pushing the views programmatically as stated above, but on iOS 8.x I have a problem:

https://dl.dropboxusercontent.com/u/17257636/Sharing/tableProb2.mov

on iOS 7 the static tableview shows well

**Comment by fahlout** [comment]
Addressing your first issue as shown in your video: This issue has is not a PageMenu or static table view issue. Your navigation bar is set to translucent it seems like which causes the offset issue.

Second issue: Yes, viewWillAppear is currently not called on the actual controller in page menu after coming back from a pushed view controller. I haven't found a simple way to implement that yet unfortunately. So for now you will need to pass your data in a different way unfortunately until a nice clean way to call view will appear on the underlying controller is worked out.

**Comment by wizmeister** [comment]
Thank you for the useful information @fahlout !!!

**Comment by fahlout** [comment]
I know it's not quite what you were looking for but I'm working on making the experience when pushing something better so that eventually viewWillAppear will be called automatically

**Comment by wizmeister** [comment]
I get it! Again, thank you for the wonderful controller and the continuous updates and  support!

**Comment by TangSirOnGit** [comment]
@fahlout  @wizmeister 
 I have added  ‘var parentNavigationController : UINavigationController?’ to the collectionViewController step by step as you described. but when i click a cell in the collectionviewcontroller，the function " collectionView(collectionView: UICollectionView, didSelectItemAtIndexPath indexPath: NSIndexPath)" was not called.

**Comment by Bautistax** [comment]
In didSelectItemAtIndexPath
make sure your calling parentNavigation
Example : 
parentNavigationController?.pushViewController(viewController, animated: true)

**Comment by TangSirOnGit** [comment]
@Bautistax  thanks, there‘s some thing wrong in my collectionview layout.

**Comment by Bautistax** [comment]
easier way is to do the switch method to call every collection cell

**Comment by alex521** [comment]
hi, how can I from pushed view controller back to parent view controller?
self.navigationController?.popViewControllerAnimated(true) got warning :
popViewControllerAnimated: called on <UINavigationController 0x7febc8640bf0> while an existing transition or presentation is occurring; the navigation stack will not be updated.

**Comment by lawgimenez** [comment]
This should be well documented about doing a push segue for all those beginners. Include it in the README that using a segue on the storyboard is not necessary.

**Comment by MatthewYork** [comment]
Beginning in PageMenu 2.0.0, we have added an initializer that obfuscates away storyboard boilerplate. If there are any new problems, please feel free to open a new issue!
