### ISSUE TITLE
Dimantions of tableview change when run the app.

### ISSUE THREAD

**Issue by AaoIi** [uacaps/PageMenu#87]
I've an issue with this library, lets deep into the problem  :

Lets say I've tableview in view controller 1 under the first tab which is taking 550 height so there will be an empty space at the bottom for the ad which is 50 height and 320 width .

i place the ad in the main view controller where i define my controllers and add it as subview after adding page menu add subview. to be in the bottom and take the 50 with 320 . 

*Even without the ad, i just wanted the tableview to stay 550 height when the app runs.

But the problem is when i run the app the tableview takes more than 550 to the bottom like 580 out of 600 of height, and i have to navigate to the second tab and back to the first one, and then the dimensions looks right and correct of the tableview .  

I'm confused of why this is happening !!! 

This is when the app runs : 
![1](https://cloud.githubusercontent.com/assets/9898307/9194900/5619e084-4027-11e5-9cba-1979485bcfca.PNG)
this is when i nav to the second tab and then to first : 
![2](https://cloud.githubusercontent.com/assets/9898307/9194901/5648c8e0-4027-11e5-94e3-c2db1cf4a907.PNG)

**Comment by kapoorsahil** [comment]
Similar problem with me.

**Comment by DlugiBugi** [comment]
Hey, I had the same issue, and I think I Found the reason. The _controllerScrollView is beeing created with frame:

_controllerScrollView.frame = CGRectMake(0.0, _menuHeight, self.view.frame.size.width, self.view.frame.size.height - _menuHeight);

So it's 'under' the menuScrollView, but later on, constraints are added:
 NSString *controllerScrollView_constraint_V_Format = [NSString stringWithFormat:@"V:|-0-[controllerScrollView]-0-|"]; 
So basically the menu will be not above but on top of the controllerScrollView, and this is what the control is expecting later on, when adding contentViewControllers.

The reason that the bottom part of a ViewController is cut out at the beginig is because the constraints hasn't  updated the view frame yet.

Simple fix,change initial frame:
    //_controllerScrollView.frame = CGRectMake(0.0, _menuHeight, self.view.frame.size.width, self.view.frame.size.height - _menuHeight);
 _controllerScrollView.frame = CGRectMake(0.0, 0.0, self.view.frame.size.width, self.view.frame.size.height);

**Comment by AaoIi** [comment]
Thanks , it works very well :)
